language: cpp
sudo: false

matrix:

  include:

  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - doxygen
        - python
        - libmpich-dev
        - libxml2-dev
        - libblas-dev
        - fftw3
        - cmake
        - cmake-data
        - liblapack-dev
        - g++-6
        - gcc-6
    env:
      - GMX_DOUBLE=OFF
      - GMX_MPI=OFF
      - GMX_THREAD_MPI=ON

before_install:
  - uname -a
  - apt list --installed
  - dpkg-query -L doxygen
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

script:
  - mkdir build && pushd build && cmake -DBUILD_TESTING=ON -DGMX_DOUBLE=$GMX_DOUBLE -DGMX_MPI=$GMX_MPI -DGMX_THREAD_MPI=$GMX_THREAD_MPI .. && make -j4
  - make check

