language: cpp
sudo: false

# The Travis-CI ccache feature sets up replacements for the system compilers, but we just want to use
# it as a wrapper, so we'll use the basic directory caching option.
#cache: ccache
# If we run into problems with colliding caches, we can force distinct caches with an environment variable.
# E.g. env:
#        - CACHE_NAME=JOB1
cache:
  apt: true
  directories:
    - $HOME/.ccache_gromacs
# It may be important to separately store the caches for different build configurations and set CCACHE_DIR
os: linux

# The `cpp` Travis image can generate a build matrix with `env` and `compiler` lists.
# To get a matrix for multiple compiler versions or MPI implementations, we will need to
# build the matrix explicitly.
# https://stackoverflow.com/a/44054333/5351807
matrix:
  # Instead of automatic matrix expansion, just specify the list of configurations to include
  include:
    # thread-MPI with gcc-6
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ccache
            - cmake
            - cmake-data
            - doxygen
            - g++-6
            - gcc-6
            - libblas-dev
            - libfftw3-dev
            - liblapack-dev
            - libxml2-dev
      env:
        - MATRIX_EVAL="GMX_DOUBLE=OFF && GMX_MPI=OFF && GMX_THREAD_MPI=ON && CC=`which gcc-6` && CXX=`which g++-6` && export CCACHE_DIR=$HOME/.ccache_gromacs"
    # MPICH with gcc-4.8.5
    # It seems we may have to build MPI ourselves if we want to use any non-default compiler?
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ccache
            - cmake
            - cmake-data
            - doxygen
#            - g++-6
#            - gcc-6
            - libblas-dev
            - libcr-dev
            - libfftw3-dev
            - liblapack-dev
            - libmpich-dev
            - libxml2-dev
            - mpich
      env:
        - MATRIX_EVAL="GMX_DOUBLE=OFF && GMX_MPI=ON && GMX_THREAD_MPI=OFF && CC=`which mpicc` && CXX=`which mpicxx` && export CCACHE_DIR=$HOME/.ccache_gromacs"

before_install:
  - uname -a
  - apt list --installed
  - dpkg-query -L doxygen
  - eval "${MATRIX_EVAL}"
  - export CCACHE_COMPILERCHECK=content
  - ${CC} --version
  - ${CXX} --version
  - ccache -s

install:
  - pwd
  - mkdir build
  - pushd build
  - cmake -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC -DBUILD_TESTING=ON -DGMX_DOUBLE=$GMX_DOUBLE -DGMX_MPI=$GMX_MPI -DGMX_THREAD_MPI=$GMX_THREAD_MPI ..
  - sleep 2 # give a couple of seconds for generated source files to be clearly "in the past"
  - make -j2 && make -j2 tests
  - popd
  - ccache -s

script:
  - pwd
  - pushd build
  - make -j2 check
  - popd
